# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron:  '0 0 * * *'
    
env:
  DISCORD_SECRET : ${{ secrets.DISCORD_SECRET }}
  REDDIT_CLIENT_ID : ${{ secrets.REDDIT_CLIENT_ID }}
  REDDIT_CLIENT_SECRET : ${{ secrets.REDDIT_CLIENT_SECRET }}
  REDDIT_USERNAME : ${{ secrets.REDDIT_USERNAME }}
  REDDIT_PASSWORD : ${{ secrets.REDDIT_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14.15.0
    - run: npm ci
    - name: Run
      run: npm run scheduled
